# 06. Exception Filter

- Nest에는 애플리케이션 전체에서 처리되지 않은 모든 예외를 처리하는 예외 계층이 내장되어있다.
- 코드에서 처리되지 않은 예외가 발생하면 이 계층에서 이를 포착하여 적절한 사용자 친화적인 응답을 자동으로
  전송한다.
- 기본적으로 이 작업은 내장된 전역 예외 필터에 의해 수행되며,이 필터는 HttpException 유형
  (및 그 하위 클래스)의 예외를 처리합니다.
- 예외가 인식되지 않는 경우(HttpException 또는 HttpException에서 상속하는 클래스도 아닌 경우),
  기본 제공 예외 필터는 다음과 같은 기본 JSON 응답을 생성합니다:

```json
{
  "statusCode": 500,
  "message": "Internal server error"
}
```

> 전역 예외 필터는 부분적으로 http-errors 라이브러리를 지원한다. 기본적으로 statusCode 및
> 메시지 속성을 포함하는 모든 예외가 올바르게 채워지고 응답으로 다시 전송됩니다.
> (인식할 수 없는 예외의 경우 기본값인 InternalServerErrorException 대신).

## Throwing standard exceptions

Nest는 @nestjs/common 패키지에서 노출되는 기본 제공 HttpException 클래스를 제공합니다.

일반적인 HTTP REST/GraphQL API 기반 애플리케이션의 경우 특정 오류 조건이 발생할 때
표준 HTTP 응답 객체를 전송하는 것이 가장 좋습니다.

예제 코드

```ts
@Get()
async findAll() {
  throw new HttpException('Forbidden', HttpStatus.FORBIDDEN);
}
```

> HttpStatus는 @nestjs/common 패키지에서 가져온 헬퍼 열거형이다.

```json
{
  "statusCode": 403,
  "message": "Forbidden"
}
```

HttpException 생성자는 응답을 결정하는 두 개의 필수 인수를 받습니다.

- response: JSON 응답 본문. 문자열 또는 객체일 수 있다.
- status: HTTP 상태 코드

기본적으로 JSON 응답 본문에는 두 가지 속성이 포함되어 있습니다:

- statusCode: 기본적으로 status 인수에 제공된 HTTP 상태 코드를 사용
- message: 상태에 따른 HTTP 오류에 대한 간단한 설명

오류 원인을 제공하는 데 사용할 수 있는 세 번째 생성자 인수(선택 사항)인 옵션이 있습니다. 이 원인 객체는
응답 객체로 직렬화되지는 않지만 로깅 목적으로 유용할 수 있으며, HttpException을 발생시킨 내부 오류에
대한 중요한 정보를 제공합니다.

```ts
@Get()
async findAll() {
  try {
    await this.service.findAll()
  } catch (error) {
    throw new HttpException({
      status: HttpStatus.FORBIDDEN,
      error: 'This is a custom message',
    }, HttpStatus.FORBIDDEN, {
      cause: error
    });
  }
}
```

```json
{
  "status": 403,
  "error": "This is a custom message"
}
```

## Custom exceptions

- 대부분의 경우 사용자 정의 예외를 작성할 필요가 없습니다.
- 사용자 정의 예외를 작성해야 하는 경우에는 사용자 정의 예외가 기본 HttpException 클래스에서 상속되는
  자체 예외 계층 구조를 만드는 것이 좋습니다. 이 접근 방식을 사용하면 Nest가 예외를 인식하고 오류
  응답을 자동으로 처리합니다.

```ts
export class ForbiddenException extends HttpException {
  constructor() {
    super('Forbidden', HttpStatus.FORBIDDEN);
  }
}
```

## Built-in HTTP exceptions

@nestjs/common 에서 제공하는 기본 내장 예외 클래스가 있다.

- BadRequestException
- UnauthorizedException
- NotFoundException
- ForbiddenException
- NotAcceptableException
- RequestTimeoutException
- ConflictException
- GoneException
- HttpVersionNotSupportedException
- PayloadTooLargeException
- UnsupportedMediaTypeException
- UnprocessableEntityException
- InternalServerErrorException
- NotImplementedException
- ImATeapotException
- MethodNotAllowedException
- BadGatewayException
- ServiceUnavailableException
- GatewayTimeoutException
- PreconditionFailedException

모든 기본 제공 예외는 옵션 매개변수를 사용하여 오류 원인과 오류 설명을 모두 제공할 수도 있습니다.

```ts
throw new BadRequestException('Something bad happened', {
  cause: new Error(),
  description: 'Some error description',
});
```

```json
{
  "message": "Something bad happened",
  "error": "Some error description",
  "statusCode": 400
}
```

## Exception filters

기본 제공 예외 필터가 많은 경우를 자동으로 처리할 수 있습니다.

하지만, 예외 계층을 완전히 제어하고 싶을 수도 있습니다.

예를 들어 로깅을 추가하거나 일부 동적 요인에 따라 다른 JSON 스키마를 사용하고 싶을 수 있습니다.
예외 필터는 바로 이러한 목적을 위해 설계되었습니다. 예외 필터를 사용하면 정확한 제어 흐름과 클라이언트에
다시 전송되는 응답의 내용을 제어할 수 있습니다.

이를 위해서는 기본 플랫폼의 요청 및 응답 객체에 액세스해야 합니다. 요청 객체에 액세스하여 원본 URL을
가져와 로깅 정보에 포함시킬 수 있습니다. Response 객체를 사용하여 response.json() 메서드를
사용하여 전송된 응답을 직접 제어할 것입니다.

```ts
// http-exception.filter.ts
import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
} from '@nestjs/common';
import { Request, Response } from 'express';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    const status = exception.getStatus();

    response.status(status).json({
      statusCode: status,
      timestamp: new Date().toISOString(),
      path: request.url,
    });
  }
}
```

> 모든 예외 필터는 일반 ExceptionFilter\<T> 인터페이스를 구현해야 합니다.
> 이를 위해서는 catch(exception: T, host: ArgumentsHost) 메서드에 지정된 서명을 제공해야
> 합니다. T는 예외의 유형을 나타냅니다.

## Binding filters

```ts
@Post()
@UseFilters(new HttpExceptionFilter())
async create(@Body() createCatDto: CreateCatDto) {
  throw new ForbiddenException();
}

// or

@Post()
@UseFilters(HttpExceptionFilter)
async create(@Body() createCatDto: CreateCatDto) {
  throw new ForbiddenException();
}
```

Catch() 데코레이터와 마찬가지로 단일 필터 인스턴스 또는 쉼표로 구분된 필터 인스턴스 목록을 받을 수
있습니다.

위의 두번 째 코드에서는 여기서는 HttpExceptionFilter 인스턴스를 대신 생성했습니다.
또는 인스턴스 대신 클래스를 전달하여 인스턴스화에 대한 책임을 프레임워크에 맡기고 의존성 주입을
활성화할 수도 있습니다.

> 가능하면 인스턴스 대신 클래스를 사용하여 필터를 적용하는 것을 선호합니다. Nest는 전체 모듈에서
> 동일한 클래스의 인스턴스를 쉽게 재사용할 수 있으므로 메모리 사용량을 줄일 수 있습니다.

예외 필터는 컨트롤러/리졸버/게이트웨이의 메서드 범위, 컨트롤러 범위 또는 전역 범위 등 다양한 수준에서
범위를 지정할 수 있습니다.

```ts
@UseFilters(new HttpExceptionFilter())
export class CatsController {}
```

전역으로 만들기

```ts
// main.ts

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalFilters(new HttpExceptionFilter());
  await app.listen(3000);
}
bootstrap();
```

> useGlobalFilters() 메서드는 게이트웨이 또는 하이브리드 애플리케이션에 대한 필터를 설정하지 않는다.

전역 범위 필터는 모든 컨트롤러와 모든 라우트 핸들러에 대해 전체 애플리케이션에서 사용됩니다.
종속성 주입과 관련하여, 모듈 외부에서 등록된 전역 필터는 모든 모듈의 컨텍스트 외부에서 수행되므로
종속성을 주입할 수 없습니다. 이 문제를 해결하기 위해 다음 구성을 사용하여 모든 모듈에서 직접 전역 범위
필터를 등록할 수 있습니다.

```ts
// app.module.ts

import { Module } from '@nestjs/common';
import { APP_FILTER } from '@nestjs/core';

@Module({
  providers: [
    {
      provide: APP_FILTER,
      useClass: HttpExceptionFilter,
    },
  ],
})
export class AppModule {}
```

## Catch everything

처리되지 않은 모든 예외를 잡으려면(예외 유형에 관계없이) @Catch() 데코레이터의 매개 변수 목록을
비워 두세요.

아래 예시에서는 HTTP 어댑터를 사용하여 응답을 전달하고 플랫폼별 객체(요청 및 응답)를 직접 사용하지
않으므로 플랫폼에 구애받지 않는 코드가 있습니다.

```ts
import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { HttpAdapterHost } from '@nestjs/core';

@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  constructor(private readonly httpAdapterHost: HttpAdapterHost) {}

  catch(exception: unknown, host: ArgumentsHost): void {
    // In certain situations `httpAdapter` might not be available in the
    // constructor method, thus we should resolve it here.
    const { httpAdapter } = this.httpAdapterHost;

    const ctx = host.switchToHttp();

    const httpStatus =
      exception instanceof HttpException
        ? exception.getStatus()
        : HttpStatus.INTERNAL_SERVER_ERROR;

    const responseBody = {
      statusCode: httpStatus,
      timestamp: new Date().toISOString(),
      path: httpAdapter.getRequestUrl(ctx.getRequest()),
    };

    httpAdapter.reply(ctx.getResponse(), responseBody, httpStatus);
  }
}
```
